name: Build

# Controls when the workflow will run
on:
  push:
    branches: ["wasm"]
  pull_request:
    branches: ["wasm"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: "stable"
          targets: "wasm32-unknown-unknown"

      # Runs a set of commands using the runners shell
      - name: Build
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: gtav-load-remover
          path: ./target/wasm32-unknown-unknown/release/gtav-load-remover.wasm
